### ISSUE TITLE
Rundeck Crashed File does not exist

### ISSUE THREAD

**Issue by levisbakalinsky** [harlanbarnes/lita-rundeck#6]
When running the run deck command, I'm getting the following error:
https://gist.github.com/anonymous/0bcbd9b665e1aea5a4aa

I'm using the following gems:
https://gist.github.com/levisbakalinsky/973f5cf3d200e71de802

Would love some advice. Thanks.

**Comment by harlanbarnes** [comment]
Hi there! Sorry for the delayed response. So looking at the stack trace, it appears that this:

```
/app/local/simonsays/.gem/ruby/2.0/gems/lita-rundeck-0.0.1/lib/lita/handlers/rundeck.rb:417:in `get'
```

is failing because the response from rundeck doesn't look like XML. I could definitely be handling this better (and will leave this ticket open to remind me to do so).

But looking at the xml-simple code, it seems to check what is passed to ```xml_in``` and if it is matches the regex ```/<.*?>/m``` then it will treat it like a string. If it doesn't match the regex, it treats it like a file on the local filesystem.

Looking here at the output you got:

```
File does not exist: .
```

comes from this [line]( https://github.com/maik/xml-simple/blob/v1.1.5/lib/xmlsimple.rb#L99) and that seems to indicate that the filename is an empty string.

So I can only guess that the output that the plugin is getting back from rundeck is empty. But why that's empty, I'm not sure.

Could you have a look at the Rundeck server logs and see if there's anything obvious on that side?

**Comment by levisbakalinsky** [comment]
Thanks for getting back to me.

So my lita config looks as follows. I made sure that i can telnet to
rundeck from the the lita box, just to confirm that i don't have any
issues with networking.

config.handlers.rundeck.url = "http://rundeck-dev.domain.com:4440"
config.handlers.rundeck.token = "XXXXXXXX"
config.handlers.rundeck.api_debug = true

What is really strange is that i don't see lita connecting to to rundeck
at all. See log info below. Any idea why i'm not seeing anything in the
logs? Thank you for taking time to help with this.

[rundeck.log]

2015-04-27 22:05:03,770 [main] INFO grails.app.conf.BootStrap - Starting
Rundeck 2.4.1-1... 2015-04-27 22:05:03,774 [main] INFO
grails.app.conf.BootStrap - using rdeck.base config property:
/var/lib/rundeck 2015-04-27 22:05:03,783 [main] INFO
grails.app.conf.BootStrap - loaded configuration:
/etc/rundeck/framework.properties 2015-04-27 22:05:03,852 [main] INFO
grails.app.conf.BootStrap - RSS feeds disabled

[rundeck.api.log]

[2015-04-27 22:10:58,799] 24.43.XX.XXX http form 12 [controller:api]
"GET /api" (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3)
AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17)

[service.log] nohup: ignoring input WARNING: HTTPS is not enabled,
specify
-Drundeck.ssl.config=/var/lib/rundeck/server/config/ssl.properties to
enable. 2015-04-27 22:04:48.831:INFO:oejs.Server:jetty-7.6.0.v20120127
2015-04-27 22:04:50.584:INFO:oejw.StandardDescriptorProcessor:NO JSP
Support for /, did not find org.apache.jasper.servlet.JspServlet
2015-04-27 22:04:51.517:INFO:/:Initializing Spring root
WebApplicationContext INFO BootStrap: Starting Rundeck 2.4.1-1... INFO
BootStrap: using rdeck.base config property: /var/lib/rundeck INFO
BootStrap: loaded configuration: /etc/rundeck/framework.properties INFO
BootStrap: RSS feeds disabled 2015-04-27
22:05:04.309:INFO:oejsh.ContextHandler:started
o.e.j.w.WebAppContext{/,file:/var/lib/rundeck/exp/webapp/},/var/lib/rundeck/exp/webapp
2015-04-27 22:05:04.359:INFO:/:Initializing Spring FrameworkServlet
'grails' 2015-04-27 22:05:04.387:INFO:oejs.AbstractConnector:Started
SelectChannelConnector@0.0.0.0:4440

Kindest Regards, Levis Bakalinsky

**Comment by harlanbarnes** [comment]
Well, unfortunately, nothing jumps out at me there. Our install is over https and on the normal port so I'll try to get setup one on http and no port over the next couple of days to see if there is any difference I can notice. It could be that I'm not passing something correctly for https or non-default ports.

At the very least, I need some debug right [here](https://github.com/harlanbarnes/lita-rundeck/blob/master/lib/lita/handlers/rundeck.rb#L412). If nothing else, I'll work up a release that adds that and we can try to see what (if anything) we are getting back from the http object.

**Comment by justintime** [comment]
Just wanted to leave a note that I'm encountering this as well, over HTTPS.  I'm running rundeck version 2.4.0-1.  I'm new to lita, but know ruby fairly well.  I've got some other things to track down, but I should get a chance sometime this week to get some time to dig into this.

**Comment by justintime** [comment]
I'm pretty sure this is a Rundeck configuration issue.  When lita hits the API, Rundeck is sending a 302 redirect to the login page.  I haven't tracked down the fix yet, but I was wondering if @levisbakalinsky was using the ldap module for Rundeck?  I am.

**Comment by justintime** [comment]
I take that back, it was lita-rundeck.  The URL being formed looks like this ```https://rundeck.mydomain.com//api/1/projects&authtoken=xxxxx```  Note the double forward slash between the hostname and the api.  Replacing that double slash with a single one makes everything work for me.

**Comment by levisbakalinsky** [comment]
@justintime, not using ldap. Have you tracked down where in the code the fix would need to be applied?

**Comment by justintime** [comment]
Yes, see PR #7

**Comment by harlanbarnes** [comment]
Ah, excellent thanks for finding that. I'm away now, but I can merge and upload tonight.

In the short term, you should just be able to drop the trailing slash from the rundeck URL in your config. Right?

**Comment by justintime** [comment]
Nope, I checked and I didn't have a slash in my config. That means there's
a slash at the beginning of that path variable, at least in some requests.
I figured the gsub would be the best way to ensure I didn't break anything
else.

**Comment by harlanbarnes** [comment]
Ah, right I see now. Wonder why it doesn't break in my setup. I guess it's some rundeck difference.

**Comment by justintime** [comment]
I know that Apache and Nginx both handle double slashes transparently.
Likely some update rundeck put into their routing at some point.

**Comment by harlanbarnes** [comment]
Ah, right. I hadn't thought of the Apache angle. That's likely it since I have Apache there (for terminating SSL and acting as a reverse proxy).

I've released 0.0.2 with #7 in it. I'm going to leave this open to get a better error around this for future instances of not getting XML back from rundeck when we expect it. And I need to work on #1 this week too. Parental duties have been getting in the way.

Anyway, thank you both for identifying this and fixing it.

**Comment by justintime** [comment]
Just tested with 0.0.2 and all is good to go.  Thanks!

**Comment by harlanbarnes** [comment]
In v0.0.3 I added [this](https://github.com/harlanbarnes/lita-rundeck/commit/172d726498134c3b067fbaff241bad97b3c7e675#diff-02ec43b07014aa1838c698e5b681614fR437) to catch the situation where rundeck (or anything in between) vomits out something that's not XML. (And thus `xmlsimple` doesn't presume it's a file to give us the misleading error that slowed us down on this a bit.) If something non-XML is responded, it flips on the API debug for that response to get the request and response into the logs. Hopefully that will do it.
